source = undefined;
light = new BulbLight(obj_bulb_controller.renderer, spr_cone_light, 0, x, y);
//light.xscale = 1.5;
//light.yscale = 1.5;
light.blend = #f9ffd4;
light.angle = image_angle;
xscale = 1;
yscale = 1;
sprite = spr_cone_light;